export const COUNTRY_NAMES: Record<string, string> = {
  TR: 'Turkey',
  IN: 'India',
  BR: 'Brazil',
  ZA: 'South Africa',
  MX: 'Mexico',
  AR: 'Argentina',
  PH: 'Philippines',
  ID: 'Indonesia',
  EG: 'Egypt',
  NG: 'Nigeria',
  PK: 'Pakistan',
  BD: 'Bangladesh',
  VN: 'Vietnam',
  CO: 'Colombia',
  PE: 'Peru',
  UA: 'Ukraine',
  PL: 'Poland',
  RO: 'Romania',
  HU: 'Hungary',
  CZ: 'Czech Republic',
  BG: 'Bulgaria',
  RS: 'Serbia',
  TH: 'Thailand',
  MY: 'Malaysia',
  GR: 'Greece',
  PT: 'Portugal',
  ES: 'Spain',
  IT: 'Italy',
  KR: 'South Korea',
  TW: 'Taiwan',
  CL: 'Chile',
};
