-- Profiles Table
create table public.profiles (
  id uuid references auth.users on delete cascade primary key,
  email text not null,
  full_name text,
  subscription_status text default 'inactive',
  stripe_customer_id text,
  stripe_subscription_id text,
  plan_type text default 'free',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Projects Table
create table public.projects (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references auth.users on delete cascade not null,
  name text not null,
  domain text not null,
  is_active boolean default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Project Settings Table
create table public.project_settings (
  id uuid default gen_random_uuid() primary key,
  project_id uuid references projects on delete cascade not null,
  banner_title text not null default 'Welcome',
  banner_text text not null default 'Check out our special offer!',
  banner_cta text not null default 'Claim Offer',
  banner_theme text not null default 'dark',
  banner_position text not null default 'bottom',
  primary_color text not null default '#000000',
  tier2_discount integer not null default 0,
  tier2_coupon text not null default '',
  tier2_countries text[] not null default '{}',
  tier3_discount integer not null default 0,
  tier3_coupon text not null default '',
  tier3_countries text[] not null default '{}',
  tier4_discount integer not null default 0,
  tier4_coupon text not null default '',
  tier4_countries text[] not null default '{}'
);

-- Analytics Table
create table public.analytics (
  id bigint generated by default as identity primary key,
  project_id uuid references projects on delete cascade not null,
  country_code text not null,
  event_type text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Automatic Profile Creation Trigger
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, email, full_name)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Disable RLS temporarily or setup simple policies so you can read/write without complex rules for now
alter table public.profiles disable row level security;
alter table public.projects disable row level security;
alter table public.project_settings disable row level security;
alter table public.analytics disable row level security;
